spring:
  datasource:
#    url: jdbc:mysql://mysql-container:3306/dropzonedb?serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/dropzonedb?serverTimezone=Asia/Seoul
    username: root
#    password: dropzoned110
    password: 8032
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssafyd110@gmail.com
    password: qzvzxehofrkhhfat
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update  # 서버 환경에 맞게 테이블 검증
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL용 Hibernate Dialect 추가
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true  # SQL 쿼리 로깅

#  redis:
#    host: redis-container
#    port: 6379

  thymeleaf:
    cache: false  # Thymeleaf 캐시 비활성화

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    key: Dr@pZoneKey2024!@#$


