version: '3.8'

services:
  mysql:
    image: mysql:8.0.20
    restart: always
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=dropzoned110
      - MYSQL_DATABASE=dropzone-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql

  redis:
    image: redis:7.4-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
